name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'

  - title: '📱 Android'
    label: 'android'

  - title: ' Ios'
    label: 'ios'

  - title: '🖥 Desktop'
    label: 'desktop'

  - title: '🌐 Web'
    label: 'wasm'

  - title: '🐛 Bug Fixes'
    label: 'bugfix'

  - title: '🧰 Maintenance'
    label: 'chore'

  - title: '📚 Documentation'
    label: 'documentation'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## What’s Changed

  $CHANGES