[versions]
# Plugin Versions
kotlin = "2.3.20"
androidGrdlePlugin = "9.1.0"
jetbrainsCompose = "1.10.2"
mavenPublish = "0.36.0"
binaryCompatibilityValidator = "0.18.1"

# Library Versions
composeMaterial3 = "1.10.0-alpha05"
kotlinxBrowser = "0.5.0"
annotation = "1.9.1"
oshiCore = "6.10.0"
startupRuntime = "1.2.0"
androidXCore = "1.18.0"

# sampleApp Versions
androidxAppcompat = "1.7.1"
androidxActivityCompose = "1.13.0"
androidXCompose = "1.10.5"

[libraries]
# KDeviceInfo module libraries
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidXCore" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshiCore" }

startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinxBrowser" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }

compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrainsCompose" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrainsCompose" }
compose-desktop = { module = "org.jetbrains.compose.desktop:desktop-jvm", version.ref = "jetbrainsCompose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMaterial3" }

# Gradle plugin artifacts (for build-logic compileOnly)
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGrdlePlugin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jetbrainsCompose" }
compose-compiler-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
mavenPublish-gradlePlugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublish" }
binaryCompatibilityValidator-gradlePlugin = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "binaryCompatibilityValidator" }

# sampleApp module libraries
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
compose-uitooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidXCompose" }


[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
androidLibrary = { id = "com.android.library", version.ref = "androidGrdlePlugin" }
androidApplication = { id = "com.android.application", version.ref = "androidGrdlePlugin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidator" }
